### ISSUE TITLE
shouldn't raw::Library::open be unsafe?

### ISSUE THREAD

**Issue by domenpk** [OpenByteDev/dlopen2#5]
(Issue also in upstream, unmaintained? unsafe: https://github.com/szymonwieloch/rust-dlopen/issues/48)

I think `open` should probably be marked `unsafe`, because it could call a unsafe function, although not directly.

For example, below code demonstrates a constructor function is called on library load (no `unsafe` code needed):

```bash
cargo new dlopen2-test
cd dlopen2-test/

cat > hello.c << EOF
#include <stdio.h>

void __attribute__ ((constructor)) hello(void)
{
        printf("hello from C\n");
}
EOF

gcc -Wall -shared -fPIC -o hello.so hello.c
cat > src/main.rs << EOF
extern crate dlopen2;
use dlopen2::raw::Library;

fn main() {
    let lib = Library::open("./hello.so").unwrap();
}
EOF

cargo add dlopen2
cargo run

# some cargo outputs, ends with this print from C code
hello from C
```

**Comment by OpenByteDev** [comment]
I dont think it should be unsafe because by your logic every function that takes a function pointer should also be unsafe, as they too could call an unsafe function further down?

**Comment by domenpk** [comment]
I have though about this, and I don't quite agree.

Taking an **unsafe** function pointer and calling it would most likely mean the calling function should be marked unsafe (can't think of a counter-example, would be interested in one). However, if the passed function pointer is not marked unsafe, this should be fine.

An example that points in your favour are OS operations (direct execution, or writing to special files that would overwrite an executable image in RAM) - these are not marked unsafe after all. Maybe these are somewhat fine, because the impact is more commonly understood, although I still don't like it. Arguably maybe they should be, since when I do security reviews, I will look for these operations, as that's where vulnerabilities often are.
